import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";

import { Button, DetailView, Icon, Layout } from "@components";
import normalizeQueryParam from "@lib/normalizeQueryParam";

export default function DetailPage() {
  const router = useRouter();
  const slug = normalizeQueryParam(router.query.slug);

  useEffect(() => {
    router.prefetch("/");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!slug) return <p>Pokemon not foud</p>;

  return (
    <>
      <Head>
        <title>
          Pokédex Details | {slug?.replace(/(^|\s)\S/g, (t) => t.toUpperCase())}
        </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout size="sm">
        <Link href="/">
          <Button>
            <Icon name="back" />
          </Button>
        </Link>
        <DetailView slug={slug ?? ""} />
      </Layout>
    </>
  );
}
