import AppsIcon from "@mui/icons-material/AppsRounded";
import FavoriteIcon from "@mui/icons-material/FavoriteBorderRounded";
import Box from "@mui/joy/Box";
import Tab, { tabClasses } from "@mui/joy/Tab";
import TabList from "@mui/joy/TabList";
import TabPanel from "@mui/joy/TabPanel";
import Tabs from "@mui/joy/Tabs";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import { Layout, ListView, Navigation } from "@components";

export default function FavoritesPage() {
  return (
    <>
      <Head>
        <title>Favorites - Pokedex</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <h1>Pokedex</h1>
        <div style={{ marginBottom: "1rem" }}>
          <Navigation />
        </div>
        <ListView isFavorite />
      </Layout>
    </>
  );
}
