import Head from "next/head";
import { PokemonList } from "../src/components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Pokedex</h1>
        <PokemonList />
      </main>
    </div>
  );
}
