import Head from "next/head";

import { Layout, ListView, Navigation } from "@components";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <h1>Pokedex</h1>
        <div style={{ marginBottom: "1rem" }}>
          <Navigation />
        </div>
        <ListView />
      </Layout>
    </>
  );
}
