import Head from "next/head";

import { Layout, ListView } from "@components";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout title="Pokédex">
        <ListView />
      </Layout>
    </>
  );
}
